improve pre-commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -32,23 +32,23 @@ if [ "$allownonascii" != "true" ] &&
 	test $(git diff --cached --name-only --diff-filter=A -z $against |
 	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
+	echo "Error: Attempt to add a non-ASCII file name."
 	exit 1
 fi
 
+has_whitespace=$(git diff-index --check $against --)
+
 # If there are whitespace errors, print the offending file names and fail.
-git diff-index --check --cached $against --
+if [[ $has_whitespace ]]; then
+	echo $has_whitespace
+	exit 1
+fi
 
 # Runs my pre-commit programs
-
-./redis/pre-commit.sh
+dirs=( "redis" )
+for dir in "${dirs[@]}"
+do
+	if [[ $(git --no-pager diff --name-only -- $dir) ]]; then
+		./$dir/pre-commit.sh
+	fi
+done
